// --- BANCO DE DADOS (Suas 100 frases) ---
const conselhosDB = [
    { "id": 1, "texto": "A vida é 10% o que acontece com você e 90% como você reage a isso." },
    { "id": 2, "texto": "Quem tem um porquê, suporta quase qualquer como." },
    { "id": 3, "texto": "O único modo de fazer um excelente trabalho é amar o que você faz." },
    { "id": 4, "texto": "Não conte os dias, faça os dias contarem." },
    { "id": 5, "texto": "A melhor maneira de prever o futuro é inventá-lo." },
    { "id": 6, "texto": "O sucesso é ir de fracasso em fracasso sem perder o entusiasmo." },
    { "id": 7, "texto": "Seja a mudança que você deseja ver no mundo." },
    { "id": 8, "texto": "A jornada de mil milhas começa com um único passo." },
    { "id": 9, "texto": "Não espere o momento perfeito, pegue o momento e torne-o perfeito." },
    { "id": 10, "texto": "A persistência realiza o impossível." },
    { "id": 11, "texto": "O maior risco é não correr nenhum risco." },
    { "id": 12, "texto": "A simplicidade é o último grau de sofisticação." },
    { "id": 13, "texto": "Acredite que você pode, e você já está no meio do caminho." },
    { "id": 14, "texto": "Caia sete vezes, levante-se oito." },
    { "id": 15, "texto": "O que não nos mata nos torna mais fortes." },
    { "id": 16, "texto": "Tudo o que você sempre quis está do outro lado do medo." },
    { "id": 17, "texto": "A mente é tudo. Você se torna aquilo que você pensa." },
    { "id": 18, "texto": "A felicidade não é algo pronto. Ela vem de suas próprias ações." },
    { "id": 19, "texto": "Não encontre defeitos, encontre soluções." },
    { "id": 20, "texto": "Se você quer viver uma vida feliz, amarre-se a um objetivo." },
    { "id": 21, "texto": "O aprendizado nunca esgota a mente." },
    { "id": 22, "texto": "Feito é melhor que perfeito." },
    { "id": 23, "texto": "Não deixe que o ruído das opiniões dos outros cale a sua própria voz interior." },
    { "id": 24, "texto": "A sorte favorece a mente preparada." },
    { "id": 25, "texto": "O tempo é o recurso mais escasso e, a menos que seja gerenciado, nada mais pode ser." },
    { "id": 26, "texto": "Trabalhe duro em silêncio, deixe o sucesso ser o seu barulho." },
    { "id": 27, "texto": "As dificuldades preparam pessoas comuns para destinos extraordinários." },
    { "id": 28, "texto": "O futuro pertence àqueles que acreditam na beleza de seus sonhos." },
    { "id": 29, "texto": "Não tenha medo de desistir do bom para perseguir o ótimo." },
    { "id": 30, "texto": "O que você faz hoje pode melhorar todos os seus amanhãs." },
    { "id": 31, "texto": "Seja corajoso o suficiente para viver a vida de forma criativa." },
    { "id": 32, "texto": "A única pessoa que você está destinado a se tornar é a pessoa que você decide ser." },
    { "id": 33, "texto": "A paciência é amarga, mas seu fruto é doce." },
    { "id": 34, "texto": "A motivação nos faz começar. O hábito nos faz continuar." },
    { "id": 35, "texto": "A disciplina é a ponte entre metas e realizações." },
    { "id": 36, "texto": "Um navio no porto está seguro, mas não é para isso que os navios são feitos." },
    { "id": 37, "texto": "Se você não planeja, está planejando fracassar." },
    { "id": 38, "texto": "A ação é a chave fundamental para todo o sucesso." },
    { "id": 39, "texto": "A vida encolhe ou se expande em proporção à sua coragem." },
    { "id": 40, "texto": "Fale menos, faça mais." },
    { "id": 41, "texto": "Erros são a prova de que você está tentando." },
    { "id": 42, "texto": "A comparação é o ladrão da alegria." },
    { "id": 43, "texto": "Foque naquilo que você pode controlar." },
    { "id": 44, "texto": "Ninguém pode fazer você se sentir inferior sem o seu consentimento." },
    { "id": 45, "texto": "Comece onde você está. Use o que você tem. Faça o que puder." },
    { "id": 46, "texto": "O segredo para avançar é começar." },
    { "id": 47, "texto": "Para ser insubstituível, deve-se sempre ser diferente." },
    { "id": 48, "texto": "O fracasso é a oportunidade de começar de novo, com mais inteligência." },
    { "id": 49, "texto": "O talento vence jogos, mas o trabalho em equipe e a inteligência vencem campeonatos." },
    { "id": 50, "texto": "Não busque o sucesso, busque ter valor." },
    { "id": 51, "texto": "Você perde 100% dos tiros que não dá." },
    { "id": 52, "texto": "A melhor vingança é um sucesso estrondoso." },
    { "id": 53, "texto": "Onde não há luta, não há força." },
    { "id": 54, "texto": "Viva como se fosse morrer amanhã. Aprenda como se fosse viver para sempre." },
    { "id": 55, "texto": "O amor não se vê com os olhos, mas com a mente." },
    { "id": 56, "texto": "Aqueles que não conseguem mudar de ideia não conseguem mudar nada." },
    { "id": 57, "texto": "O conhecimento fala, mas a sabedoria escuta." },
    { "id": 58, "texto": "Coragem é a resistência ao medo, o domínio do medo, e não a ausência dele." },
    { "id": 59, "texto": "Nossa maior glória não está em nunca cair, mas em nos levantar cada vez que caímos." },
    { "id": 60, "texto": "Seja bondoso sempre que possível. É sempre possível." },
    { "id": 61, "texto": "A verdadeira medida de um homem não se vê nos momentos de conforto, mas na controvérsia." },
    { "id": 62, "texto": "O único lugar onde o sucesso vem antes do trabalho é no dicionário." },
    { "id": 63, "texto": "Sua atitude, não sua aptidão, determinará sua altitude." },
    { "id": 64, "texto": "A imaginação é mais importante que o conhecimento." },
    { "id": 65, "texto": "A única verdadeira sabedoria é saber que você não sabe nada." },
    { "id": 66, "texto": "O segredo da felicidade não é fazer sempre o que se quer, mas querer sempre o que se faz." },
    { "id": 67, "texto": "Você não precisa ver toda a escada, apenas dê o primeiro passo." },
    { "id": 68, "texto": "Transforme suas feridas em sabedoria." },
    { "id": 69, "texto": "Um homem criativo é motivado pelo desejo de alcançar, não pelo desejo de vencer os outros." },
    { "id": 70, "texto": "O impossível é apenas uma palavra grande jogada por homens pequenos." },
    { "id": 71, "texto": "A maneira de começar é parar de falar e começar a fazer." },
    { "id": 72, "texto": "As pessoas costumam dizer que a motivação não dura. Bem, nem o banho, por isso recomendamos diariamente." },
    { "id": 73, "texto": "Somente aqueles que ousam falhar grandemente podem alcançar grandemente." },
    { "id": 74, "texto": "Não se trata de quão duro você bate, mas de quão duro você pode ser atingido e continuar seguindo em frente." },
    { "id": 75, "texto": "A pior solidão é não ser confortável com você mesmo." },
    { "id": 76, "texto": "Resiliência é aceitar sua nova realidade, mesmo que seja menos boa que a que você tinha antes." },
    { "id": 77, "texto": "Sucesso é ter o que você quer. Felicidade é querer o que você tem." },
    { "id": 78, "texto": "Nós somos o que fazemos repetidamente. A excelência, portanto, não é um ato, mas um hábito." },
    { "id": 79, "texto": "Você nunca é velho demais para definir outro objetivo ou sonhar um novo sonho." },
    { "id": 80, "texto": "Sempre parece impossível até que seja feito." },
    { "id": 81, "texto": "Faça o seu melhor. Ninguém pode fazer mais do que isso." },
    { "id": 82, "texto": "Tente ser um arco-íris na nuvem de alguém." },
    { "id": 83, "texto": "Cada dia é uma nova oportunidade para mudar sua vida." },
    { "id": 84, "texto": "Seu tempo é limitado, não o desperdice vivendo a vida de outra pessoa." },
    { "id": 85, "texto": "Um investimento em conhecimento paga os melhores juros." },
    { "id": 86, "texto": "Mude seus pensamentos e você mudará seu mundo." },
    { "id": 87, "texto": "As coisas mais belas do mundo não podem ser vistas nem tocadas, devem ser sentidas com o coração." },
    { "id": 88, "texto": "Otimismo é a fé que leva à realização. Nada pode ser feito sem esperança e confiança." },
    { "id": 89, "texto": "A vida não é sobre se encontrar. A vida é sobre se criar." },
    { "id": 90, "texto": "Quando você chegar ao fim de sua corda, dê um nó nela e segure-se." },
    { "id": 91, "texto": "Grandes coisas nunca vêm de zonas de conforto." },
    { "id": 92, "texto": "A diferença entre o comum e o extraordinário é o pequeno extra." },
    { "id": 93, "texto": "Sua vida não melhora por acaso, melhora pela mudança." },
    { "id": 94, "texto": "Sonhe grande e ouse falhar." },
    { "id": 95, "texto": "Se as coisas derem errado, não vá com elas." },
    { "id": 96, "texto": "Nunca deixe o medo de errar impedir que você jogue." },
    { "id": 97, "texto": "O sucesso normalmente vem para quem está ocupado demais para procurar por ele." },
    { "id": 98, "texto": "Não seja empurrado por seus problemas. Seja guiado por seus sonhos." },
    { "id": 99, "texto": "A dúvida mata mais sonhos do que o fracasso jamais matará." },
    { "id": 100, "texto": "Acredite em si mesmo e tudo será possível." }
];

// --- LÓGICA DO SORTEIO ---
const btn = document.getElementById('btn-dice');
const idElement = document.getElementById('advice-id');
const textoElement = document.getElementById('advice-text');

function gerarConselhoLocal() {
    const indice = Math.floor(Math.random() * conselhosDB.length);
    const conselhoAtual = conselhosDB[indice];
    idElement.innerText = `ADVICE #${conselhoAtual.id}`;
    textoElement.innerText = `"${conselhoAtual.texto}"`;
}

btn.addEventListener('click', gerarConselhoLocal);
gerarConselhoLocal();